server:
  port: 8081

  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata-order?serverTimezone=Asia/Shanghai
    username: root
    password: password

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: seata-order

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml